# Generated by Django 4.0.5 on 2022-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=75)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
