# Generated by Django 4.0.5 on 2022-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0003_delete_communication_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapany_name', models.CharField(max_length=75)),
                ('courses_provided', models.CharField(max_length=75)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=75)),
                ('course_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=75)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(max_length=75)),
                ('Features', models.CharField(max_length=250)),
                ('course_through', models.CharField(max_length=75)),
                ('course_type', models.CharField(max_length=75)),
                ('course_category', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry_db',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
