# Generated by Django 4.0.5 on 2022-06-24 09:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0004_company_details_course_categories_course_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
