# Generated by Django 4.0.5 on 2022-06-29 09:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0005_alter_company_details_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=8)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_number_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('p_address', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=8)),
                ('education', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=45)),
                ('specialization', models.CharField(max_length=45)),
                ('university_college', models.CharField(max_length=125)),
                ('course_type', models.CharField(max_length=20)),
                ('passingout_year', models.IntegerField()),
                ('grading_system', models.CharField(max_length=15)),
                ('grading_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=8)),
                ('enrollment_date', models.DateField()),
                ('course_enrolled', models.CharField(max_length=8)),
                ('enrollment_institute', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='company_details',
            name='institute_id',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AddField(
            model_name='course_details',
            name='What_you_learn',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AddField(
            model_name='course_details',
            name='course_id',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AddField(
            model_name='course_details',
            name='description',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AddField(
            model_name='course_details',
            name='institute_id',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='father_name',
            field=models.CharField(default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='gender',
            field=models.CharField(default='NA', max_length=6),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='marital_status',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='mother_name',
            field=models.CharField(default='NA', max_length=75),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='registration_id',
            field=models.CharField(default='NA', max_length=8),
        ),
    ]
