# Generated by Django 4.0.5 on 2022-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0005_alter_company_details_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=75)),
                ('feature_name', models.CharField(max_length=75)),
                ('feature_value', models.CharField(max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='course_details',
            name='Features',
        ),
        migrations.AddField(
            model_name='company_details',
            name='contact_person',
            field=models.CharField(default='not updated', max_length=75),
        ),
    ]
