# Generated by Django 4.0.5 on 2022-06-30 05:28

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0006_communication_details_educational_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='course_banner',
            field=models.ImageField(default=sqlalchemy.sql.expression.null, upload_to='uploads/'),
        ),
    ]
