# Generated by Django 4.0.5 on 2022-06-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0006_company_features_remove_course_details_features_and_more'),
        ('courcompadmin', '0007_course_details_course_banner'),
    ]

    operations = [
    ]
