# Generated by Django 4.0.5 on 2022-06-30 12:08

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0008_merge_20220630_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='course_banner',
            field=models.ImageField(default=sqlalchemy.sql.expression.null, upload_to='uploads'),
        ),
    ]
