# Generated by Django 4.0.5 on 2022-07-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0009_alter_course_details_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='phone_number',
            field=models.CharField(default='NA', max_length=8),
        ),
    ]
