# Generated by Django 4.0.5 on 2022-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0011_alter_company_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='contact_person',
            field=models.CharField(default='NA', max_length=75),
        ),
    ]
