# Generated by Django 4.0.5 on 2022-07-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0012_alter_company_details_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='course_banner',
        ),
    ]
