# Generated by Django 4.0.5 on 2022-07-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courcompadmin', '0014_course_details_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='course_banner',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
